// <auto-generated />
using System;
using ConcessionariaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConcessionariaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929203352_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ConcessionariaApi.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Combustivel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEmUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<long>("Quilometragem")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Disponivel");

                    b.HasIndex("Marca", "Modelo");

                    b.ToTable("Veiculos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 2024,
                            Combustivel = "Flex",
                            Cor = "Prata",
                            CriadoEmUtc = new DateTime(2026, 9, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            Disponivel = true,
                            Marca = "Toyota",
                            Modelo = "Corolla Altis",
                            Preco = 158900.00m,
                            Quilometragem = 12500L
                        },
                        new
                        {
                            Id = 2,
                            Ano = 2025,
                            Combustivel = "Flex",
                            Cor = "Branco",
                            CriadoEmUtc = new DateTime(2026, 9, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            Disponivel = true,
                            Marca = "Volkswagen",
                            Modelo = "T-Cross Highline",
                            Preco = 172490.00m,
                            Quilometragem = 8200L
                        },
                        new
                        {
                            Id = 3,
                            Ano = 2023,
                            Combustivel = "Flex",
                            Cor = "Azul",
                            CriadoEmUtc = new DateTime(2026, 9, 29, 12, 0, 0, 0, DateTimeKind.Utc),
                            Disponivel = false,
                            Marca = "Chevrolet",
                            Modelo = "Onix Premier",
                            Preco = 98900.00m,
                            Quilometragem = 31000L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
